# Generated by Django 4.0.5 on 2022-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_address_alter_profile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='a', max_length=25),
            preserve_default=False,
        ),
    ]
